---
services:
  immobilienverwaltung:
    image: ghcr.io/dav354/immobilienverwaltung:latest
    restart: unless-stopped
    container_name: immobilienverwaltung
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - data:/data
    ports:
      - 8080:8080
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=immobilienverwaltung
      - DB_USER=myuser
      - DB_PASSWORD=mypassword
      - DEMO_MODE=true
      - ADMIN=admin
      - ADMIN_PW=password

  db:
    image: docker.io/postgres:16-alpine
    restart: unless-stopped
    container_name: immobilienverwaltung-db
    volumes:
      - postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=myuser
      - POSTGRES_PASSWORD=mypassword
      - POSTGRES_DB=immobilienverwaltung
    healthcheck:
      test: ["CMD", "pg_isready"]
      interval: 5s
      timeout: 20s
      retries: 5

volumes:
  postgres:
  data: