name: Build Documentation

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-docs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Nix
        uses: cachix/install-nix-action@v27
        with:
          nix_path: nixpkgs=channel:nixos-unstable

      - name: Build Documentation
        run: |
          nix-shell default.nix

      - name: Create or Update GitHub Release
        id: create_release
        uses: softprops/action-gh-release@v2
        with:
          files: docs/documentation.pdf
          tag_name: latest
          release_name: Latest Documentation
        env:
          GITHUB_TOKEN: ${{ secrets.GHCR_PAT }}