name: Build Documentation

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-docs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Nix
        uses: cachix/install-nix-action@v27
        with:
          nix_path: nixpkgs=channel:nixos-unstable

      - name: Set up Nix cache
        uses: nix-community/cache-nix-action@v5
        with:
          path: /nix/store
          key: ${{ runner.os }}-nix-${{ hashFiles('**/*.nix') }}
          restore-keys: |
            ${{ runner.os }}-nix-

      - name: Build Documentation
        run: |
          nix-shell default.nix

      - name: Create or Update GitHub Release
        id: create_release
        uses: softprops/action-gh-release@v1
        with:
          files: docs/documentation.pdf
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}